AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution with TLS (ACM) in front of an HTTP origin.

Parameters:
  DomainName:
    Type: String
    Description: Public domain for the distribution (e.g., testapp-devops.tidepool.org)
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Route53 hosted zone ID that contains DomainName
  OriginDomainName:
    Type: String
    Description: Origin DNS name (e.g., EC2 public DNS or ALB DNS)
  OriginPath:
    Type: String
    Default: ''
    Description: Optional origin path prefix
  OriginPort:
    Type: Number
    Default: 8000
    Description: Origin HTTP port (matches app port)
  PriceClass:
    Type: String
    Default: PriceClass_100
    AllowedValues: [PriceClass_100, PriceClass_200, PriceClass_All]
    Description: CloudFront price class

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cert'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: !Ref PriceClass
        DefaultRootObject: ''
        Origins:
          - Id: app-origin
            DomainName: !Ref OriginDomainName
            OriginPath: !Ref OriginPath
            CustomOriginConfig:
              HTTPPort: !Ref OriginPort
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: app-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref DomainName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cf'

  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  DistributionId:
    Value: !Ref Distribution
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
  CertificateArn:
    Value: !Ref Certificate
  Route53Record:
    Value: !Ref DnsRecord

